In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [2]:
import os
import pandas as pd
import glob

In [3]:
df = pd.read_csv('/gdrive/MyDrive/Colab Notebooks/total_df.csv')

In [4]:
df.columns

Index(['YYYYMMDD', 'HHMMSS', 'MNG_NO', 'IF_IDX', 'AVG_INBPS', 'MIN_INBPS',
       'MAX_INBPS', 'AVG_OUTBPS', 'MIN_OUTBPS', 'MAX_OUTBPS', 'AVG_INPPS',
       'MIN_INPPS', 'MAX_INPPS', 'AVG_OUTPPS', 'MIN_OUTPPS', 'MAX_OUTPPS',
       'AVG_INERR', 'MIN_INERR', 'MAX_INERR', 'AVG_OUTERR', 'MIN_OUTERR',
       'MAX_OUTERR', 'AVG_CRC', 'MIN_CRC', 'MAX_CRC', 'AVG_COLLISION',
       'MIN_COLLISION', 'MAX_COLLISION', 'AVG_INDROP', 'MIN_INDROP',
       'MAX_INDROP', 'AVG_OUTDROP', 'MIN_OUTDROP', 'MAX_OUTDROP',
       'AVG_INNUPPS', 'MIN_INNUPPS', 'MAX_INNUPPS', 'AVG_OUTNUPPS',
       'MIN_OUTNUPPS', 'MAX_OUTNUPPS', 'AVG_INDISCARD', 'MIN_INDISCARD',
       'MAX_INDISCARD', 'AVG_OUTDISCARD', 'MIN_OUTDISCARD', 'MAX_OUTDISCARD',
       'AVG_INMCASTPPS', 'MIN_INMCASTPPS', 'MAX_INMCASTPPS', 'AVG_OUTMCASTPPS',
       'MIN_OUTMCASTPPS', 'MAX_OUTMCASTPPS', 'AVG_INBCASTPPS',
       'MIN_INBCASTPPS', 'MAX_INBCASTPPS', 'AVG_OUTBCASTPPS',
       'MIN_OUTBCASTPPS', 'MAX_OUTBCASTPPS'],
      dtype='object')

In [5]:
import matplotlib.pyplot as plt

In [12]:
for col in df.columns:
    print(f'{col} : {len(df[col].unique())}')

YYYYMMDD : 7
HHMMSS : 288
MNG_NO : 10686
IF_IDX : 26
AVG_INBPS : 4413650
MIN_INBPS : 4413650
MAX_INBPS : 4413650
AVG_OUTBPS : 1567959
MIN_OUTBPS : 1567959
MAX_OUTBPS : 1567959
AVG_INPPS : 44142
MIN_INPPS : 44142
MAX_INPPS : 44142
AVG_OUTPPS : 287257
MIN_OUTPPS : 287257
MAX_OUTPPS : 287257
AVG_INERR : 1302
MIN_INERR : 1302
MAX_INERR : 1302
AVG_OUTERR : 1065
MIN_OUTERR : 1065
MAX_OUTERR : 1065
AVG_CRC : 1
MIN_CRC : 1
MAX_CRC : 1
AVG_COLLISION : 1
MIN_COLLISION : 1
MAX_COLLISION : 1
AVG_INDROP : 1
MIN_INDROP : 1
MAX_INDROP : 1
AVG_OUTDROP : 1
MIN_OUTDROP : 1
MAX_OUTDROP : 1
AVG_INNUPPS : 897
MIN_INNUPPS : 897
MAX_INNUPPS : 897
AVG_OUTNUPPS : 287257
MIN_OUTNUPPS : 287257
MAX_OUTNUPPS : 287257
AVG_INDISCARD : 28382
MIN_INDISCARD : 28382
MAX_INDISCARD : 28382
AVG_OUTDISCARD : 709
MIN_OUTDISCARD : 709
MAX_OUTDISCARD : 709
AVG_INMCASTPPS : 1
MIN_INMCASTPPS : 1
MAX_INMCASTPPS : 1
AVG_OUTMCASTPPS : 1
MIN_OUTMCASTPPS : 1
MAX_OUTMCASTPPS : 1
AVG_INBCASTPPS : 1
MIN_INBCASTPPS : 1
MAX_INBCASTPPS : 1
AVG_OUTBCASTPPS : 1
MIN_OUTBCASTPPS : 1
MAX_OUTBCASTPPS : 1

In [13]:
df.shape

(23195128, 58)

In [14]:
df.head()

   YYYYMMDD  HHMMSS  MNG_NO  ...  AVG_OUTBCASTPPS  MIN_OUTBCASTPPS  MAX_OUTBCASTPPS
0  20210620  235500   26641  ...                0                0                0
1  20210620   85500    5505  ...                0                0                0
2  20210620   85000    5505  ...                0                0                0
3  20210620   84500    5505  ...                0                0                0
4  20210620   84000    5505  ...                0                0                0

[5 rows x 58 columns]

In [15]:
df.tail()

          YYYYMMDD  HHMMSS  ...  MIN_OUTBCASTPPS  MAX_OUTBCASTPPS
23195123  20210626  150500  ...                0                0
23195124  20210626  150500  ...                0                0
23195125  20210626  150500  ...                0                0
23195126  20210626  150500  ...                0                0
23195127  20210626     500  ...                0                0

[5 rows x 58 columns]

In [7]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline

In [8]:
from collections import Counter

## Get Count for Each Date

In [9]:
check_cols = ['INBPS', 'OUTBPS', 
              'INDISCARD', 'OUTDISCARD', 
              'INERR', 'OUTERR', 
              'INNUPPS', 'OUTNUPPS', 
              'INPPS', 'OUTPPS']

check_cols

['INBPS',
 'OUTBPS',
 'INDISCARD',
 'OUTDISCARD',
 'INERR',
 'OUTERR',
 'INNUPPS',
 'OUTNUPPS',
 'INPPS',
 'OUTPPS']

In [10]:
INBPS_COLS = []
OUTBPS_COLS = []
INDISCARD_COLS = []
OUTDISCARD_COLS = []
INERR_COLS = []
OUTERR_COLS = []
INNUPPS_COLS = []
OUTNUPPS_COLS = []
INPPS_COLS = []
OUTPPS_COLS = []

In [11]:
cols = 'INBPS'
'AVG_' + cols

'AVG_INBPS'

In [12]:
for cols in check_cols:
    if cols == 'INBPS':
        INBPS_COLS.append('MIN_'+cols)
        INBPS_COLS.append('MAX_'+cols)
        INBPS_COLS.append('AVG_'+cols)
    elif cols == 'OUTBPS':
        OUTBPS_COLS.append('MIN_'+cols)
        OUTBPS_COLS.append('MAX_'+cols)
        OUTBPS_COLS.append('AVG_'+cols)
    elif cols == 'INDISCARD':
        INDISCARD_COLS.append('MIN_'+cols)
        INDISCARD_COLS.append('MAX_'+cols)
        INDISCARD_COLS.append('AVG_'+cols)
    elif cols == 'OUTDISCARD':
        OUTDISCARD_COLS.append('MIN_'+cols)
        OUTDISCARD_COLS.append('MAX_'+cols)
        OUTDISCARD_COLS.append('AVG_'+cols)
    elif cols == 'INERR':
        INERR_COLS.append('MIN_'+cols)
        INERR_COLS.append('MAX_'+cols)
        INERR_COLS.append('AVG_'+cols)
    elif cols == 'OUTERR':
        OUTERR_COLS.append('MIN_'+cols)
        OUTERR_COLS.append('MAX_'+cols)
        OUTERR_COLS.append('AVG_'+cols)
    elif cols == 'INNUPPS':
        INNUPPS_COLS.append('MIN_'+cols)
        INNUPPS_COLS.append('MAX_'+cols)
        INNUPPS_COLS.append('AVG_'+cols)
    elif cols == 'OUTNUPPS':
        OUTNUPPS_COLS.append('MIN_'+cols)
        OUTNUPPS_COLS.append('MAX_'+cols)
        OUTNUPPS_COLS.append('AVG_'+cols)
    elif cols == 'INPPS':
        INPPS_COLS.append('MIN_'+cols)
        INPPS_COLS.append('MAX_'+cols)
        INPPS_COLS.append('AVG_'+cols)
    elif cols == 'OUTPPS':
        OUTPPS_COLS.append('MIN_'+cols)
        OUTPPS_COLS.append('MAX_'+cols)
        OUTPPS_COLS.append('AVG_'+cols)

In [13]:
INBPS_COLS

['MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS']

In [14]:
COLS = [INBPS_COLS, OUTBPS_COLS, 
        INDISCARD_COLS, OUTDISCARD_COLS, 
        INERR_COLS, OUTERR_COLS, 
        INNUPPS_COLS, OUTNUPPS_COLS, 
        INPPS_COLS, OUTPPS_COLS]

COLS

[['MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS'],
 ['MIN_OUTBPS', 'MAX_OUTBPS', 'AVG_OUTBPS'],
 ['MIN_INDISCARD', 'MAX_INDISCARD', 'AVG_INDISCARD'],
 ['MIN_OUTDISCARD', 'MAX_OUTDISCARD', 'AVG_OUTDISCARD'],
 ['MIN_INERR', 'MAX_INERR', 'AVG_INERR'],
 ['MIN_OUTERR', 'MAX_OUTERR', 'AVG_OUTERR'],
 ['MIN_INNUPPS', 'MAX_INNUPPS', 'AVG_INNUPPS'],
 ['MIN_OUTNUPPS', 'MAX_OUTNUPPS', 'AVG_OUTNUPPS'],
 ['MIN_INPPS', 'MAX_INPPS', 'AVG_INPPS'],
 ['MIN_OUTPPS', 'MAX_OUTPPS', 'AVG_OUTPPS']]

In [15]:
dates_df = pd.DataFrame(df['YYYYMMDD'])
dates_df.head()

   YYYYMMDD
0  20210620
1  20210620
2  20210620
3  20210620
4  20210620

In [16]:
df[['YYYYMMDD','MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS']]#.iloc[:,1:]

          YYYYMMDD  MIN_INBPS  MAX_INBPS  AVG_INBPS
0         20210620      66992      66992      66992
1         20210620      37824      37824      37824
2         20210620       8792       8792       8792
3         20210620     144336     144336     144336
4         20210620      45656      45656      45656
...            ...        ...        ...        ...
23195123  20210626    1619560    1619560    1619560
23195124  20210626     133448     133448     133448
23195125  20210626    1511248    1511248    1511248
23195126  20210626      43824      43824      43824
23195127  20210626      55800      55800      55800

[23195128 rows x 4 columns]

In [17]:
dates = list(df['YYYYMMDD'].unique())
dates

[20210620, 20210621, 20210622, 20210623, 20210624, 20210625, 20210626]

In [18]:
#['MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS']

for COL in COLS:
    print(COL)
    print(f'Comparing MIN and MAX : {pd.Series(df[COL[0]]==df[COL[1]]).unique()}')
    print(f'Comparing MIN and AVG : {pd.Series(df[COL[0]]==df[COL[2]]).unique()}')
    print(f'Comparing MAX and AVG : {pd.Series(df[COL[1]]==df[COL[2]]).unique()}')
    print('------end------')

['MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_OUTBPS', 'MAX_OUTBPS', 'AVG_OUTBPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_INDISCARD', 'MAX_INDISCARD', 'AVG_INDISCARD']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_OUTDISCARD', 'MAX_OUTDISCARD', 'AVG_OUTDISCARD']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_INERR', 'MAX_INERR', 'AVG_INERR']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_OUTERR', 'MAX_OUTERR', 'AVG_OUTERR']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_INNUPPS', 'MAX_INNUPPS', 'AVG_INNUPPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_OUTNUPPS', 'MAX_OUTNUPPS', 'AVG_OUTNUPPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_INPPS', 'MAX_INPPS', 'AVG_INPPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------
['MIN_OUTPPS', 'MAX_OUTPPS', 'AVG_OUTPPS']
Comparing MIN and MAX : [ True]
Comparing MIN and AVG : [ True]
Comparing MAX and AVG : [ True]
------end------

In [19]:
pd.Series(df['MIN_INBPS']==df['MAX_INBPS']).unique()

array([ True])

In [20]:
for COL in COLS:
    print(COL)
    print(df[['YYYYMMDD']+COL].head())
    print(df[['YYYYMMDD']+COL].tail())
    print('------end------')

['MIN_INBPS', 'MAX_INBPS', 'AVG_INBPS']
   YYYYMMDD  MIN_INBPS  MAX_INBPS  AVG_INBPS
0  20210620      66992      66992      66992
1  20210620      37824      37824      37824
2  20210620       8792       8792       8792
3  20210620     144336     144336     144336
4  20210620      45656      45656      45656
          YYYYMMDD  MIN_INBPS  MAX_INBPS  AVG_INBPS
23195123  20210626    1619560    1619560    1619560
23195124  20210626     133448     133448     133448
23195125  20210626    1511248    1511248    1511248
23195126  20210626      43824      43824      43824
23195127  20210626      55800      55800      55800
------end------
['MIN_OUTBPS', 'MAX_OUTBPS', 'AVG_OUTBPS']
   YYYYMMDD  MIN_OUTBPS  MAX_OUTBPS  AVG_OUTBPS
0  20210620       36576       36576       36576
1  20210620       36192       36192       36192
2  20210620       28104       28104       28104
3  20210620       43680       43680       43680
4  20210620       50720       50720       50720
          YYYYMMDD  MIN_OUTBPS  MAX_OUTBPS  AVG_OUTBPS
23195123  20210626      279856      279856      279856
23195124  20210626       16752       16752       16752
23195125  20210626       38144       38144       38144
23195126  20210626       72704       72704       72704
23195127  20210626       69464       69464       69464
------end------
['MIN_INDISCARD', 'MAX_INDISCARD', 'AVG_INDISCARD']
   YYYYMMDD  MIN_INDISCARD  MAX_INDISCARD  AVG_INDISCARD
0  20210620              0              0              0
1  20210620              0              0              0
2  20210620              0              0              0
3  20210620              0              0              0
4  20210620              0              0              0
          YYYYMMDD  MIN_INDISCARD  MAX_INDISCARD  AVG_INDISCARD
23195123  20210626              0              0              0
23195124  20210626              0              0              0
23195125  20210626              0              0              0
23195126  20210626              0              0              0
23195127  20210626              0              0              0
------end------
['MIN_OUTDISCARD', 'MAX_OUTDISCARD', 'AVG_OUTDISCARD']
   YYYYMMDD  MIN_OUTDISCARD  MAX_OUTDISCARD  AVG_OUTDISCARD
0  20210620               0               0               0
1  20210620               0               0               0
2  20210620               0               0               0
3  20210620               0               0               0
4  20210620               0               0               0
          YYYYMMDD  MIN_OUTDISCARD  MAX_OUTDISCARD  AVG_OUTDISCARD
23195123  20210626               0               0               0
23195124  20210626               0               0               0
23195125  20210626               0               0               0
23195126  20210626               0               0               0
23195127  20210626               0               0               0
------end------
['MIN_INERR', 'MAX_INERR', 'AVG_INERR']
   YYYYMMDD  MIN_INERR  MAX_INERR  AVG_INERR
0  20210620          0          0          0
1  20210620          0          0          0
2  20210620          0          0          0
3  20210620          0          0          0
4  20210620          0          0          0
          YYYYMMDD  MIN_INERR  MAX_INERR  AVG_INERR
23195123  20210626          0          0          0
23195124  20210626          0          0          0
23195125  20210626          0          0          0
23195126  20210626          0          0          0
23195127  20210626          0          0          0
------end------
['MIN_OUTERR', 'MAX_OUTERR', 'AVG_OUTERR']
   YYYYMMDD  MIN_OUTERR  MAX_OUTERR  AVG_OUTERR
0  20210620           0           0           0
1  20210620           0           0           0
2  20210620           0           0           0
3  20210620           0           0           0
4  20210620           0           0           0
          YYYYMMDD  MIN_OUTERR  MAX_OUTERR  AVG_OUTERR
23195123  20210626           0           0           0
23195124  20210626           0           0           0
23195125  20210626           0           0           0
23195126  20210626           0           0           0
23195127  20210626           0           0           0
------end------
['MIN_INNUPPS', 'MAX_INNUPPS', 'AVG_INNUPPS']
   YYYYMMDD  MIN_INNUPPS  MAX_INNUPPS  AVG_INNUPPS
0  20210620            0            0            0
1  20210620            0            0            0
2  20210620            0            0            0
3  20210620            0            0            0
4  20210620            0            0            0
          YYYYMMDD  MIN_INNUPPS  MAX_INNUPPS  AVG_INNUPPS
23195123  20210626            0            0            0
23195124  20210626            0            0            0
23195125  20210626            0            0            0
23195126  20210626            0            0            0
23195127  20210626            0            0            0
------end------
['MIN_OUTNUPPS', 'MAX_OUTNUPPS', 'AVG_OUTNUPPS']
   YYYYMMDD  MIN_OUTNUPPS  MAX_OUTNUPPS  AVG_OUTNUPPS
0  20210620          4572          4572          4572
1  20210620            14            14            14
2  20210620            10            10            10
3  20210620            16            16            16
4  20210620            16            16            16
          YYYYMMDD  MIN_OUTNUPPS  MAX_OUTNUPPS  AVG_OUTNUPPS
23195123  20210626            72            72            72
23195124  20210626            11            11            11
23195125  20210626            27            27            27
23195126  20210626            21            21            21
23195127  20210626            28            28            28
------end------
['MIN_INPPS', 'MAX_INPPS', 'AVG_INPPS']
   YYYYMMDD  MIN_INPPS  MAX_INPPS  AVG_INPPS
0  20210620         22         22         22
1  20210620         10         10         10
2  20210620          5          5          5
3  20210620         20         20         20
4  20210620         11         11         11
          YYYYMMDD  MIN_INPPS  MAX_INPPS  AVG_INPPS
23195123  20210626        164        164        164
23195124  20210626         14         14         14
23195125  20210626        131        131        131
23195126  20210626         17         17         17
23195127  20210626         22         22         22
------end------
['MIN_OUTPPS', 'MAX_OUTPPS', 'AVG_OUTPPS']
   YYYYMMDD  MIN_OUTPPS  MAX_OUTPPS  AVG_OUTPPS
0  20210620        4572        4572        4572
1  20210620          14          14          14
2  20210620          10          10          10
3  20210620          16          16          16
4  20210620          16          16          16
          YYYYMMDD  MIN_OUTPPS  MAX_OUTPPS  AVG_OUTPPS
23195123  20210626          72          72          72
23195124  20210626          11          11          11
23195125  20210626          27          27          27
23195126  20210626          21          21          21
23195127  20210626          28          28          28
------end------

In [ ]:
for COL in COLS:
    print(COL)
    print(df[['YYYYMMDD']+COL].head())
    print(df[['YYYYMMDD']+COL].tail())
    print('------end------')

In [21]:
vis_cols = ['AVG_INERR', 'AVG_INBPS', 'AVG_INDISCARD', 'AVG_INNUPPS', 'AVG_INPPS', 
            'AVG_OUTERR', 'AVG_OUTBPS', 'AVG_OUTDISCARD', 'AVG_OUTNUPPS', 'AVG_OUTPPS']

In [22]:
save_path = '/gdrive/MyDrive/Colab Notebooks/results/'

In [ ]:
for col in vis_cols:
    stat, _, name  = col.partition("_")
    print(stat, name)

    # define plot_df
    plot_df = df[col]

    # define fig
    fig = plt.figure()

    plot_df.plot(figsize = (12, 6))

    plt.title(f'{name}')

    plt.savefig(save_path+f"{name}_plot.png", dpi=200)

AVG INERR
AVG INBPS
AVG INDISCARD
AVG INNUPPS
AVG INPPS
AVG OUTERR
AVG OUTBPS
AVG OUTDISCARD
AVG OUTNUPPS
AVG OUTPPS

In [44]:
for vis_col in vis_cols:
    print(f'vis_col: {vis_col}')
    tmp_cols = []
    
    for col in cols:
        #print(f'>>>>>col: {col}')
        if vis_col in col:
            tmp_cols.append(col)
        
    #print(tmp_cols)
    #print('--------------------')
    tmp_df = df[tmp_cols]
    
    # make tmp dataframe
    tmp_df = pd.concat([dates_df, tmp_df], axis = 1)
    
    # for dates
    for date in dates:
        print(f'>>> plotting {date}')
        
        # use data at certain date
        date_df = tmp_df[tmp_df['YYYYMMDD']==date].iloc[:,1:]
        
        criteria = ['MAX', 'MIN', 'AVG']
        
        for c in criteria:
            
            if c == 'AVG':
                plot_df = date_df.iloc[:,0]
            elif c == 'MIN':
                plot_df = date_df.iloc[:,1]
            elif c == 'MAX':
                plot_df = date_df.iloc[:,2]
                
            # define fig
            fig = plt.figure()

            plot_df.plot(figsize = (12, 6))

            plt.title(f'{c}_{vis_col}({date}) ')

            plt.savefig(save_path+ f"/{c}_{vis_col}_{date}.png", dpi=200)
            
            plt.close('all')

vis_col: INERR
>>> plotting 20210620

IndexError: ignored

In [ ]:
for vis_col in vis_cols:
    print(f'vis_col: {vis_col}')
    tmp_cols = []
    
    for col in cols:
        #print(f'>>>>>col: {col}')
        if vis_col in col:
            tmp_cols.append(col)
        
    #print(tmp_cols)
    #print('--------------------')
    tmp_df = df[tmp_cols]
    
    # make tmp dataframe
    tmp_df = pd.concat([dates_df, tmp_df], axis = 1)
    
    # for dates
    for date in dates:
        print(f'> plotting {date}')
        
        # use data at certain date
        date_df = tmp_df[tmp_df['YYYYMMDD']==date].iloc[:,1:]
        
        criteria = ['MAX', 'MIN', 'AVG']
        
        for c in criteria:
            
            if c == 'AVG':
                plot_df = date_df.iloc[:,0]
                plot_avg = plot_df.mean()
                plot_min = plot_df.min()
                plot_max = plot_df.max()
                print(f'>> AVG(MIN): {plot_min}')
                print(f'>> AVG(AVG): {plot_avg}')
                print(f'>> AVG(MAX): {plot_max}')

            elif c == 'MIN':
                plot_df = date_df.iloc[:,1]
                plot_avg = plot_df.mean()
                plot_min = plot_df.min()
                plot_max = plot_df.max()
                print(f'>> MIN(MIN): {plot_min}')
                print(f'>> MIN(AVG): {plot_avg}')
                print(f'>> MIN(MAX): {plot_max}')
            elif c == 'MAX':
                plot_df = date_df.iloc[:,2]
                plot_avg = plot_df.mean()
                plot_min = plot_df.min()
                plot_max = plot_df.max()
                print(f'>> MAX(MIN): {plot_min}')
                print(f'>> MAX(AVG): {plot_avg}')
                print(f'>> MAX(MAX): {plot_max}')

vis_col: INERR
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 0.0009929763219236904
>> MAX(MAX): 103
>> MIN(MIN): 0
>> MIN(AVG): 0.0009929763219236904
>> MIN(MAX): 103
>> AVG(MIN): 0
>> AVG(AVG): 0.0009929763219236904
>> AVG(MAX): 103
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 0.1070327038198467
>> MAX(MAX): 9360
>> MIN(MIN): 0
>> MIN(AVG): 0.1070327038198467
>> MIN(MAX): 9360
>> AVG(MIN): 0
>> AVG(AVG): 0.1070327038198467
>> AVG(MAX): 9360
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 0.21545382251356252
>> MAX(MAX): 12166
>> MIN(MIN): 0
>> MIN(AVG): 0.21545382251356252
>> MIN(MAX): 12166
>> AVG(MIN): 0
>> AVG(AVG): 0.21545382251356252
>> AVG(MAX): 12166
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 0.1899605151255562
>> MAX(MAX): 20995
>> MIN(MIN): 0
>> MIN(AVG): 0.1899605151255562
>> MIN(MAX): 20995
>> AVG(MIN): 0
>> AVG(AVG): 0.1899605151255562
>> AVG(MAX): 20995
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 0.3504950319532711
>> MAX(MAX): 87505
>> MIN(MIN): 0
>> MIN(AVG): 0.3504950319532711
>> MIN(MAX): 87505
>> AVG(MIN): 0
>> AVG(AVG): 0.3504950319532711
>> AVG(MAX): 87505
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 0.09246079843196818
>> MAX(MAX): 16707
>> MIN(MIN): 0
>> MIN(AVG): 0.09246079843196818
>> MIN(MAX): 16707
>> AVG(MIN): 0
>> AVG(AVG): 0.09246079843196818
>> AVG(MAX): 16707
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 0.013125300391402939
>> MAX(MAX): 3539
>> MIN(MIN): 0
>> MIN(AVG): 0.013125300391402939
>> MIN(MAX): 3539
>> AVG(MIN): 0
>> AVG(AVG): 0.013125300391402939
>> AVG(MAX): 3539
vis_col: OUTDROP
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
vis_col: INNUPPS
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 1.4232476784349255
>> MAX(MAX): 230423
>> MIN(MIN): 0
>> MIN(AVG): 1.4232476784349255
>> MIN(MAX): 230423
>> AVG(MIN): 0
>> AVG(AVG): 1.4232476784349255
>> AVG(MAX): 230423
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 1.3255765156290704
>> MAX(MAX): 4693
>> MIN(MIN): 0
>> MIN(AVG): 1.3255765156290704
>> MIN(MAX): 4693
>> AVG(MIN): 0
>> AVG(AVG): 1.3255765156290704
>> AVG(MAX): 4693
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 1.300698597051876
>> MAX(MAX): 3564
>> MIN(MIN): 0
>> MIN(AVG): 1.300698597051876
>> MIN(MAX): 3564
>> AVG(MIN): 0
>> AVG(AVG): 1.300698597051876
>> AVG(MAX): 3564
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 1.3138820131438875
>> MAX(MAX): 6472
>> MIN(MIN): 0
>> MIN(AVG): 1.3138820131438875
>> MIN(MAX): 6472
>> AVG(MIN): 0
>> AVG(AVG): 1.3138820131438875
>> AVG(MAX): 6472
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 1.414565846192937
>> MAX(MAX): 8387
>> MIN(MIN): 0
>> MIN(AVG): 1.414565846192937
>> MIN(MAX): 8387
>> AVG(MIN): 0
>> AVG(AVG): 1.414565846192937
>> AVG(MAX): 8387
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 1.3606745082676048
>> MAX(MAX): 3692
>> MIN(MIN): 0
>> MIN(AVG): 1.3606745082676048
>> MIN(MAX): 3692
>> AVG(MIN): 0
>> AVG(AVG): 1.3606745082676048
>> AVG(MAX): 3692
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 1.4019500500077176
>> MAX(MAX): 4121
>> MIN(MIN): 0
>> MIN(AVG): 1.4019500500077176
>> MIN(MAX): 4121
>> AVG(MIN): 0
>> AVG(AVG): 1.4019500500077176
>> AVG(MAX): 4121
vis_col: OUTNUPPS
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 2065.437395895265
>> MAX(MAX): 33784710
>> MIN(MIN): 0
>> MIN(AVG): 2065.437395895265
>> MIN(MAX): 33784710
>> AVG(MIN): 0
>> AVG(AVG): 2065.437395895265
>> AVG(MAX): 33784710
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 10884.217727320281
>> MAX(MAX): 45275418
>> MIN(MIN): 0
>> MIN(AVG): 10884.217727320281
>> MIN(MAX): 45275418
>> AVG(MIN): 0
>> AVG(AVG): 10884.217727320281
>> AVG(MAX): 45275418
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 10274.470403238776
>> MAX(MAX): 34360111
>> MIN(MIN): 0
>> MIN(AVG): 10274.470403238776
>> MIN(MAX): 34360111
>> AVG(MIN): 0
>> AVG(AVG): 10274.470403238776
>> AVG(MAX): 34360111
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 10379.628168063316
>> MAX(MAX): 49227501
>> MIN(MIN): 0
>> MIN(AVG): 10379.628168063316
>> MIN(MAX): 49227501
>> AVG(MIN): 0
>> AVG(AVG): 10379.628168063316
>> AVG(MAX): 49227501
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 10318.102998850687
>> MAX(MAX): 46340093
>> MIN(MIN): 0
>> MIN(AVG): 10318.102998850687
>> MIN(MAX): 46340093
>> AVG(MIN): 0
>> AVG(AVG): 10318.102998850687
>> AVG(MAX): 46340093
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 9422.836515565848
>> MAX(MAX): 32470807
>> MIN(MIN): 0
>> MIN(AVG): 9422.836515565848
>> MIN(MAX): 32470807
>> AVG(MIN): 0
>> AVG(AVG): 9422.836515565848
>> AVG(MAX): 32470807
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 2315.964770284498
>> MAX(MAX): 26240727
>> MIN(MIN): 0
>> MIN(AVG): 2315.964770284498
>> MIN(MAX): 26240727
>> AVG(MIN): 0
>> AVG(AVG): 2315.964770284498
>> AVG(MAX): 26240727
vis_col: INDISCARD
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 11.453699935354793
>> MAX(MAX): 8403755
>> MIN(MIN): 0
>> MIN(AVG): 11.453699935354793
>> MIN(MAX): 8403755
>> AVG(MIN): 0
>> AVG(AVG): 11.453699935354793
>> AVG(MAX): 8403755
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 102.17135060146234
>> MAX(MAX): 3169587
>> MIN(MIN): 0
>> MIN(AVG): 102.17135060146234
>> MIN(MAX): 3169587
>> AVG(MIN): 0
>> AVG(AVG): 102.17135060146234
>> AVG(MAX): 3169587
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 109.02586151696624
>> MAX(MAX): 3894820
>> MIN(MIN): 0
>> MIN(AVG): 109.02586151696624
>> MIN(MAX): 3894820
>> AVG(MIN): 0
>> AVG(AVG): 109.02586151696624
>> AVG(MAX): 3894820
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 124.03730567319344
>> MAX(MAX): 3365716
>> MIN(MIN): 0
>> MIN(AVG): 124.03730567319344
>> MIN(MAX): 3365716
>> AVG(MIN): 0
>> AVG(AVG): 124.03730567319344
>> AVG(MAX): 3365716
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 129.86653843994765
>> MAX(MAX): 9742979
>> MIN(MIN): 0
>> MIN(AVG): 129.86653843994765
>> MIN(MAX): 9742979
>> AVG(MIN): 0
>> AVG(AVG): 129.86653843994765
>> AVG(MAX): 9742979
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 101.42783862050769
>> MAX(MAX): 3252166
>> MIN(MIN): 0
>> MIN(AVG): 101.42783862050769
>> MIN(MAX): 3252166
>> AVG(MIN): 0
>> AVG(AVG): 101.42783862050769
>> AVG(MAX): 3252166
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 16.78371724870965
>> MAX(MAX): 877271
>> MIN(MIN): 0
>> MIN(AVG): 16.78371724870965
>> MIN(MAX): 877271
>> AVG(MIN): 0
>> AVG(AVG): 16.78371724870965
>> AVG(MAX): 877271
vis_col: INBCASTPPS
> plotting 20210620
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210621
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210622
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210623
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210624
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210625
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0
> plotting 20210626
>> MAX(MIN): 0
>> MAX(AVG): 0.0
>> MAX(MAX): 0
>> MIN(MIN): 0
>> MIN(AVG): 0.0
>> MIN(MAX): 0
>> AVG(MIN): 0
>> AVG(AVG): 0.0
>> AVG(MAX): 0